Centreon\Domain\PlatformTopology\PlatformTopology:
  properties:
    id:
      type: int
      groups: [platform_topology_main]
    address:
      type: string
      groups: [platform_topology_main]
    name:
      type: string
      groups: [platform_topology_main]
    type:
      type: string
      groups: [platform_topology_main]
    parentAddress:
      type: string
      groups: [platform_topology_main]
    serverId:
      type: int
      groups: [platform_topology_main]